// 模型数据初始化

var modeldata = [
    {
        id:1,
        imgSrc:'images/center/c_start.png',
        title:'开始',
        text:'',
        associated:'start',
        resize:0,
        domJoin:1
    },
    {
        id:2,
        imgSrc:'images/center/c_ptjd.png',
        title:'普通节点',
        text:'部门领导审批',
        associated:'ptjd',
        resize:1,
        domJoin:4
    },
    {
        id:3,
        imgSrc:'images/center/c_jzjd.png',
        title:'竞争节点',
        text:'部门领导审批',
        associated:'jzjd',
        resize:1,
        domJoin:4
    },
    {
        id:4,
        imgSrc:'images/center/c_drbx.png',
        title:'多人并行',
        text:'部门领导审批',
        associated:'drbx',
        resize:1,
        domJoin:4
    },
    {
        id:5,
        imgSrc:'images/center/c_drcx.png',
        title:'多人串行',
        text:'部门领导审批',
        associated:'drcx',
        resize:1,
        domJoin:4
    },
    {
        id:6,
        imgSrc:'images/center/c_hqjd.png',
        title:'会签节点',
        text:'部门领导审批',
        associated:'hqjd',
        resize:1,
        domJoin:4
    },
    {
        id:7,
        imgSrc:'images/center/c_ywjd.png',
        title:'阅文节点',
        text:'部门领导审批',
        associated:'ywjd',
        resize:1,
        domJoin:4
    },
    {
        id:8,
        imgSrc:'images/center/c_jsrw.png',
        title:'结束任务',
        text:'部门领导审批',
        associated:'jsrw',
        resize:0,
        domJoin:4
    },
    {
        id:9,
        imgSrc:'images/center/c_jslc.png',
        title:'结束流程',
        text:'部门领导审批',
        associated:'jslc',
        resize:0,
        domJoin:4
    },
    {
        id:10,
        imgSrc:'images/center/c_jcjd.png',
        title:'决策节点',
        text:'部门领导审批',
        associated:'jcjd',
        resize:0,
        domJoin:4
    },
    {
        id:11,
        imgSrc:'images/center/c_zyjd.png',
        title:'自由节点',
        text:'部门领导审批',
        associated:'zyjd',
        resize:0,
        domJoin:4
    },
    {
        id:12,
        imgSrc:'images/center/c_dfzjd.png',
        title:'多分支节点',
        text:'部门领导审批',
        associated:'dfzjd',
        resize:0,
        domJoin:4
    },
    {
        id:13,
        imgSrc:'images/center/c_jhjd.png',
        title:'聚合节点',
        text:'部门领导审批',
        associated:'jhjd',
        resize:0,
        domJoin:4
    },
]
